#!/bin/sh

_path="$(dirname "$0")/project/GameSystems/Components"
_file="../Base/include/Components.inc"
_guardian="COMPONENTS_INC_AUTOGEN"

cd $_path
touch $_file
> $_file

echo "// ? ╔════════════════════════════╗" >> $_file
echo "// ? ║ Headers of all components  ║" >> $_file
echo "// ? ║ Generated by components.sh ║" >> $_file
echo "// ? ╚════════════════════════════╝" >> $_file
echo "#ifndef $_guardian" >> $_file
echo "#define $_guardian" >> $_file
echo >> $_file
echo "#include \"Component.inl\"" >> $_file
echo >> $_file

for _header in *
do
    echo "    #include \"$_header\"" >> $_file
done

echo >> $_file
echo "#endif /* !$_guardian */" >> $_file
echo "File: $_path/Components.inc generated."