#!/bin/sh

_path="$(dirname "$0")/project/GameSystems/Systems/include"
_file="../../Base/include/Systems.inc"
_guardian="SYSTEMS_INC_AUTOGEN"

cd $_path
touch $_file
> $_file

echo "// ? ╔══════════════════════════╗" >> $_file
echo "// ? ║ Headers of all systems   ║" >> $_file
echo "// ? ║ Generated by systems.sh  ║" >> $_file
echo "// ? ╚══════════════════════════╝" >> $_file
echo "#ifndef $_guardian" >> $_file
echo "#define $_guardian" >> $_file
echo >> $_file
echo "#include \"System.hpp\"" >> $_file
echo >> $_file

for _header in *
do
    echo "    #include \"$_header\"" >> $_file
done

echo >> $_file
echo "#endif /* !$_guardian */" >> $_file
echo "File: $_path/Components.inc generated."