#ifndef COMPONENTS_INC_
#define COMPONENTS_INC_

    #include "Component.inl"

    #include "BoxCollider.inl"    
    #include "Camera.inl"    
    #include "Collider.inl"    
    #include "MeshRenderer.inl"    
    #include "Rigidbody.inl"    
    #include "SphereCollider.inl"    
    #include "Transform.inl"
    #include "AudioListener.inl"
    #include "AudioSource.inl"

#endif /* !COMPONENTS_INC_ */
