#ifndef COMPONENTTYPE_INL_
#define COMPONENTTYPE_INL_

enum class ComponentType
{
    INVALID_TYPE = -1,
    COMPONENT = 0,
    BOX_COLLIDER,
    CAMERA,
    COLLIDER,
    MESH_RENDERER,
    RIGIDBODY,
    SPHERE_COLLIDER,
    TRANSFORM,
    AUDIO_LISTENER,
    AUDIO_SOURCE
};

#endif /* !COMPONENTTYPE_INL_ */
