// ? ╔════════════════════════════╗
// ? ║ Pre-decl of all components.║
// ? ║ Generated by components.sh ║
// ? ╚════════════════════════════╝
#ifndef COMPONENTS_PRE_DECL_INC_AUTOGEN
#define COMPONENTS_PRE_DECL_INC_AUTOGEN

class AudioListener;
class AudioSource;
class BillboardRenderer;
class Bone;
class BoxCollider;
class Camera;
class Collider;
class MeshRenderer;
class Renderer;
class Rigidbody;
class SkinnedMeshRenderer;
class SphereCollider;
class Transform;

#endif /* !COMPONENTS_PRE_DECL_INC_AUTOGEN */
