// ? ╔════════════════════════════╗
// ? ║ Pre-decl of all components.║
// ? ║ Generated by systems.sh    ║
// ? ╚════════════════════════════╝
#ifndef SYSTEMS_PRE_DECL__INC_AUTOGEN
#define SYSTEMS_PRE_DECL__INC_AUTOGEN
class AudioListenerSystem;
class AudioSourceSystem;
class BillboardRendererSystem;
class BoneSystem;
class CameraControlSystem;
class CameraSystem;
class CollisionDetectionSystem;
class CollisionDetectionSystem;
class GravitySystem;
class KinematicSystem;
class MeshRendererSystem;
#endif /* !SYSTEMS_PRE_DECL__INC_AUTOGEN */
